# This file tells netlify where the code for this project is and
# how it should build the JavaScript assets to deploy from.
[build]
  base = "front-end/"
  publish = "build/"
  command = "npm run build"
   [[redirects]]
  from = "/*"
  to = "/"
  status = 200

